### ISSUE TITLE
beforeSave() doesn't save created_by & modified_by with CakePHP 3.3.3

### ISSUE THREAD

**Issue by sourjya** [cakemanager/cakephp-utils#34]
Not sure if something changed between the version this was written for and 3.3.3. 

Upon inspecting the plugin, I see it is dependent on a configuration option named **GlobalAuth** that stores the `$this->Auth->user()` 's content. 

If I include the following statement in my `AppController.php` 's `beforeFilter()`, I can still get it work. 

```
        if( $this->Auth->user() ) {
            Configure::write( 'GlobalAuth', $this->Auth->user() );
         }
```

But if this piece of code is not manually introduced, the plugin fails to store the who-did-it data on it's own.

**Comment by bobmulder** [comment]
Sorry for the late late late delay @sourjya. Did you manage to fix this? Is the code needed? Long time ago I created this code :P I doubt if I still agree to this method. The reason is because when using MVC, the Model shouldn't be affected from the outside. Using the `GlobalAuth` (equals to the session) doesn't work conform that rule...
